export const allItems = [
    {_id: 101, title: "Computer"},
    {_id: 102, title: "Deals"},
    {_id: 103, title: "Digital Music"},
    {_id: 104, title: "Electeonic"},
    {_id: 105, title: "Girls Fasion "},
    {_id: 106, title: "Boy'Fashion "},
    {_id: 107, title: "Computer"},
    {_id: 108, title: "Deals"},
    {_id: 108, title: "Digital Music"},
    {_id: 110, title: "Electeonic"},
    {_id: 111, title: "Girls Fasion "},
    {_id: 112, title: "Health & Household"},
    {_id: 113, title: "Arts & Crafts"},
    {_id: 114, title: "Automotive"},
    {_id: 115, title: "Baby"},
    {_id: 116, title: "Books"},
    {_id: 117, title: "Boy'Fashion "},
    {_id: 118, title: "Computer"},
    {_id: 119, title: "Deals"},
    {_id: 120, title: "Digital Music"},
    {_id: 121, title: "Electeonic"},
    {_id: 122, title: "Girls Fasion "},
    {_id: 123, title: "Boy'Fashion "},
    {_id: 124, title: "Computer"},
    {_id: 125, title: "Deals"},
    {_id: 126, title: "Digital Music"},
    {_id: 127, title: "Electeonic"},
    {_id: 128, title: "Girls Fasion "},
    ];